#!/usr/bin/env python3
"""
update_data.py
--------------
Downloads Ötöslottó and Hatoslottó CSVs from szerencsejatek.hu,
parses them, and regenerates src/App.jsx with fresh embedded data.

Run manually:  python scripts/update_data.py
Run via CI:    called automatically by .github/workflows/update.yml
"""

import urllib.request
import sys
import os
import re
from datetime import datetime, timezone

OTOS_CSV_URL  = "https://bet.szerencsejatek.hu/cmsfiles/otos.csv"
HATOS_CSV_URL = "https://bet.szerencsejatek.hu/cmsfiles/hatos.csv"
TEMPLATE_PATH = os.path.join(os.path.dirname(__file__), "../src/App.template.jsx")
OUTPUT_PATH   = os.path.join(os.path.dirname(__file__), "../src/App.jsx")
MIN_YEAR      = 1998


def fetch_csv(url: str) -> list[str]:
    print(f"Fetching {url} ...")
    req = urllib.request.Request(url, headers={"User-Agent": "Mozilla/5.0"})
    with urllib.request.urlopen(req, timeout=30) as r:
        raw = r.read().decode("utf-8-sig")
    lines = [l.strip() for l in raw.splitlines() if l.strip()]
    print(f"  {len(lines)} rows downloaded.")
    return lines


def parse_otos_csv(lines: list[str]) -> tuple[list, list]:
    """Ötöslottó CSV: year;draw_num;date;jackpot_winners;...;n1;n2;n3;n4;n5
    draw   = (year, date_str, n1, n2, n3, n4, n5)
    jackpot= (year, date_str, winner_count, n1, n2, n3, n4, n5)
    """
    draws, jackpots = [], []
    for line in lines:
        parts = line.split(";")
        if len(parts) < 15:
            continue
        try:
            year = int(parts[0])
        except ValueError:
            continue
        if year < MIN_YEAR:
            continue
        date_str = parts[2].strip()
        try:
            n1, n2, n3, n4, n5 = (
                int(parts[-5]), int(parts[-4]),
                int(parts[-3]), int(parts[-2]), int(parts[-1]),
            )
        except (ValueError, IndexError):
            continue
        draws.append((year, date_str, n1, n2, n3, n4, n5))
        try:
            winners = int(parts[3])
        except (ValueError, IndexError):
            winners = 0
        if winners > 0:
            jackpots.append((year, date_str, winners, n1, n2, n3, n4, n5))
    print(f"  Ötöslottó: {len(draws)} draws, {len(jackpots)} jackpots.")
    return draws, jackpots


def parse_hatos_csv(lines: list[str]) -> tuple[list, list]:
    """Hatoslottó CSV: year;draw_num;day_name;date;jackpot_winners;...;n1;n2;n3;n4;n5;n6
    draw   = (year, date_str, n1, n2, n3, n4, n5, n6)
    jackpot= (year, date_str, winner_count, n1, n2, n3, n4, n5, n6)
    """
    draws, jackpots = [], []
    for line in lines:
        parts = line.split(";")
        if len(parts) < 19:
            continue
        try:
            year = int(parts[0])
        except ValueError:
            continue
        if year < MIN_YEAR:
            continue
        date_str = parts[3].strip()
        try:
            n1, n2, n3, n4, n5, n6 = (
                int(parts[-6]), int(parts[-5]), int(parts[-4]),
                int(parts[-3]), int(parts[-2]), int(parts[-1]),
            )
        except (ValueError, IndexError):
            continue
        draws.append((year, date_str, n1, n2, n3, n4, n5, n6))
        try:
            winners = int(parts[4])
        except (ValueError, IndexError):
            winners = 0
        if winners > 0:
            jackpots.append((year, date_str, winners, n1, n2, n3, n4, n5, n6))
    print(f"  Hatoslottó: {len(draws)} draws, {len(jackpots)} jackpots.")
    return draws, jackpots


def to_js_array(rows: list) -> str:
    parts = []
    for row in rows:
        year, date_str, *rest = row
        inner = ",".join(
            f'"{v}"' if isinstance(v, str) else str(v)
            for v in [year, date_str, *rest]
        )
        parts.append(f"[{inner}]")
    return "[" + ",".join(parts) + "]"


def build_jsx(otos_draws, otos_jackpots, hatos_draws, hatos_jackpots) -> str:
    template_path = os.path.abspath(TEMPLATE_PATH)
    if not os.path.exists(template_path):
        print(f"ERROR: Template not found at {template_path}")
        sys.exit(1)

    with open(template_path, "r", encoding="utf-8") as f:
        template = f.read()

    for placeholder in ("%%RAW_DATA%%", "%%RAW_DATA_HATOS%%"):
        if placeholder not in template:
            print(f"ERROR: {placeholder} not found in template.")
            sys.exit(1)

    updated_at = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    otos_block = (
        f'import {{ useState, useMemo }} from "react";\n\n'
        f'// Auto-generated by scripts/update_data.py — {updated_at}\n'
        f'const RAW = {to_js_array(otos_draws)};\n'
    )
    hatos_block = f'const RAW_HATOS = {to_js_array(hatos_draws)};\n'

    jsx = template.replace("%%RAW_DATA%%", otos_block)
    jsx = jsx.replace("%%RAW_DATA_HATOS%%", hatos_block)

    jsx = re.sub(
        r"const JACKPOTS = \[.*?\];",
        f"const JACKPOTS = {to_js_array(otos_jackpots)};",
        jsx, flags=re.DOTALL,
    )
    jsx = re.sub(
        r"const JACKPOTS_HATOS = \[.*?\];",
        f"const JACKPOTS_HATOS = {to_js_array(hatos_jackpots)};",
        jsx, flags=re.DOTALL,
    )

    return jsx


def main():
    otos_lines  = fetch_csv(OTOS_CSV_URL)
    hatos_lines = fetch_csv(HATOS_CSV_URL)

    otos_draws,  otos_jackpots  = parse_otos_csv(otos_lines)
    hatos_draws, hatos_jackpots = parse_hatos_csv(hatos_lines)

    jsx = build_jsx(otos_draws, otos_jackpots, hatos_draws, hatos_jackpots)

    out_path = os.path.abspath(OUTPUT_PATH)
    with open(out_path, "w", encoding="utf-8") as f:
        f.write(jsx)

    print(f"  Written → {out_path}")
    print("Done ✓")


if __name__ == "__main__":
    main()
