#!/usr/bin/env python3
"""
update_data.py
--------------
Downloads the latest Ötöslottó CSV from szerencsejatek.hu,
parses it, and regenerates src/App.jsx with fresh embedded data.

Run manually:  python scripts/update_data.py
Run via CI:    called automatically by .github/workflows/update.yml
"""

import urllib.request
import sys
import os
import re
from datetime import datetime, timezone

CSV_URL       = "https://bet.szerencsejatek.hu/cmsfiles/otos.csv"
TEMPLATE_PATH = os.path.join(os.path.dirname(__file__), "../src/App.template.jsx")
OUTPUT_PATH   = os.path.join(os.path.dirname(__file__), "../src/App.jsx")
MIN_YEAR      = 1998


def fetch_csv(url: str) -> list[str]:
    print(f"Fetching {url} ...")
    req = urllib.request.Request(url, headers={"User-Agent": "Mozilla/5.0"})
    with urllib.request.urlopen(req, timeout=30) as r:
        raw = r.read().decode("utf-8-sig")
    lines = [l.strip() for l in raw.splitlines() if l.strip()]
    print(f"  {len(lines)} rows downloaded.")
    return lines


def parse_csv(lines: list[str]) -> tuple[list, list]:
    """Returns (draws, jackpots).
    draw   = (year, date_str, n1, n2, n3, n4, n5)
    jackpot= (year, date_str, winner_count, n1, n2, n3, n4, n5)
    """
    draws    = []
    jackpots = []

    for line in lines:
        parts = line.split(";")
        if len(parts) < 15:
            continue
        try:
            year = int(parts[0])
        except ValueError:
            continue
        if year < MIN_YEAR:
            continue

        date_str = parts[2].strip()

        try:
            n1, n2, n3, n4, n5 = (
                int(parts[-5]), int(parts[-4]),
                int(parts[-3]), int(parts[-2]), int(parts[-1]),
            )
        except (ValueError, IndexError):
            continue

        draws.append((year, date_str, n1, n2, n3, n4, n5))

        try:
            winners = int(parts[3])
        except (ValueError, IndexError):
            winners = 0

        if winners > 0:
            jackpots.append((year, date_str, winners, n1, n2, n3, n4, n5))

    print(f"  {len(draws)} draws parsed, {len(jackpots)} jackpot draws found.")
    return draws, jackpots


def to_js_array(rows: list) -> str:
    parts = []
    for row in rows:
        year, date_str, *rest = row
        inner = ",".join(
            f'"{v}"' if isinstance(v, str) else str(v)
            for v in [year, date_str, *rest]
        )
        parts.append(f"[{inner}]")
    return "[" + ",".join(parts) + "]"


def build_jsx(draws: list, jackpots: list) -> str:
    template_path = os.path.abspath(TEMPLATE_PATH)
    if not os.path.exists(template_path):
        print(f"ERROR: Template not found at {template_path}")
        sys.exit(1)

    with open(template_path, "r", encoding="utf-8") as f:
        template = f.read()

    if "%%RAW_DATA%%" not in template:
        print("ERROR: %%RAW_DATA%% placeholder not found in template.")
        sys.exit(1)

    updated_at = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    data_block = (
        f'import {{ useState, useMemo }} from "react";\n\n'
        f'// Auto-generated by scripts/update_data.py — {updated_at}\n'
        f'const RAW = {to_js_array(draws)};\n'
    )

    jsx = template.replace("%%RAW_DATA%%", data_block)

    # Replace the JACKPOTS const that's baked into the template
    jsx = re.sub(
        r"const JACKPOTS = \[.*?\];",
        f"const JACKPOTS = {to_js_array(jackpots)};",
        jsx,
        flags=re.DOTALL,
    )

    return jsx


def main():
    lines          = fetch_csv(CSV_URL)
    draws, jackpots = parse_csv(lines)
    jsx            = build_jsx(draws, jackpots)

    out_path = os.path.abspath(OUTPUT_PATH)
    with open(out_path, "w", encoding="utf-8") as f:
        f.write(jsx)

    print(f"  Written → {out_path}")
    print("Done ✓")


if __name__ == "__main__":
    main()
